//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 donut-1.glb --draco 
*/

import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export function Donut(props) {
  const { nodes, materials } = useGLTF("/3dModel/donut-1.glb");
  const { camera } = useThree();
  console.log(camera.position);
  return (
    <group
      {...props}
      dispose={null}
      rotation-x={Math.PI * 2.1}
      position={[2, 1, -1]}
    >
      <mesh
        geometry={nodes.vcbjfbu_LOD0_TIER2_000_MatID_1_0.geometry}
        material={materials.Donut_vcbjfbu_Mid}
        scale={0.25}
      />
    </group>
  );
}

useGLTF.preload("/3dModel/donut-1.glb");
